[phases.setup]

[phases.install]
cmd = "bun install"

[phases.build]
cmd = "bun run build"

[phases.setupdb]
cmd = "bun run db:push && bun run db:seed"
onlyIncludeFiles = ["prisma", "db"]

[start]
cmd = "bun run start"
